(require :fiveam)

(defpackage :sb-gmp-test (:use "COMMON-LISP" :it.bese.fiveam))

(in-package :sb-gmp-test)

(def-suite sb-gmp-suite :description "Unit tests for the GMP lib interface.")

(in-suite sb-gmp-suite)

(defparameter *state* (sb-gmp:make-gmp-rstate))
(sb-gmp:rand-seed *state* 1234)

(defmacro defgenerator (name arguments &body body)
  `(defun ,name ,arguments
     (lambda () ,@body)))

(defgenerator gen-mpz (&key (limbs 5))
  (sb-gmp:random-bitcount *state* (* limbs sb-vm:n-word-bits)))

(test mpz-add "Test the mpz-add function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #xFFFFF) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (is (= (+ ta tb)
                 (sb-gmp:mpz-add ta tb))))))))

(test mpz-sub "Test the mpz-sub function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x1FFFF) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (is (= (- ta tb)
                 (sb-gmp:mpz-sub ta tb))))))))

(test mpz-mul "Test the mpz-mul function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (is (= (* ta tb)
                 (sb-gmp:mpz-mul ta tb))))))))

(test mpz-truncate "Test the mpz-tdiv function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (multiple-value-bind (ld lr)
              (truncate ta tb)
            (multiple-value-bind (gd gr)
                (sb-gmp:mpz-tdiv ta tb)
              (is (and (= ld gd)
                       (= lr gr))))))))))

(test mpz-floor "Test the mpz-fdiv function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (multiple-value-bind (ld lr)
              (floor ta tb)
            (multiple-value-bind (gd gr)
                (sb-gmp:mpz-fdiv ta tb)
              (is (and (= ld gd)
                       (= lr gr))))))))))

(test mpz-ceiling "Test the mpz-cdiv function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (multiple-value-bind (ld lr)
              (ceiling ta tb)
            (multiple-value-bind (gd gr)
                (sb-gmp:mpz-cdiv ta tb)
              (is (and (= ld gd)
                       (= lr gr))))))))))

(test mpz-gcd "Test the mpz-gcd function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (is (= (gcd ta tb)
                 (sb-gmp:mpz-gcd ta tb))))))))

(test mpz-lcm "Test the mpz-lcm function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (is (= (lcm ta tb)
                 (sb-gmp:mpz-lcm ta tb))))))))

(test mpz-isqrt "Test the mpz-isqrt function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (+ (random #x253F) 2)))
      (for-all ((a (gen-mpz :limbs limbs)))
        (is (= (isqrt a)
               (sb-gmp:mpz-sqrt a)))))))

(test mpz-mod "Test the mpz-mod function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (1+ (random #x253F))))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (b (gen-mpz :limbs limbs)))
        (let ((ta (if (zerop neg-a) a (- a)))
              (tb (if (zerop neg-b) b (- b))))
          (is (= (mod ta (abs tb))
                 (sb-gmp:mpz-mod ta tb))))))))

(test mpz-powm "Test the mpz-powm function"
  (sb-gmp:rand-seed *state* 1234)
  (dotimes (i 5)
    (let ((limbs (1+ (random #x125))))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (a (gen-mpz :limbs limbs))
                (m (gen-mpz :limbs (ceiling limbs 2))))
        (let ((e (sb-bignum:make-small-bignum (1+ (random 40))))
              (ta (if (zerop neg-a) a (- a))))
          (is (= (mod (expt ta e) m)
                 (sb-gmp:mpz-powm ta e m))))))))

(test fixed-bugs "Tests for found bugs"
  (is (= (+ #x7FFFFFFFFFFFFFFF #x7FFFFFFFFFFFFFFF)
         (sb-gmp:mpz-add #x7FFFFFFFFFFFFFFF #x7FFFFFFFFFFFFFFF)))
  (let ((a 30951488519636377404900619671461408624764773310745985021994671444676860083493)
        (b 200662724990805535745252242839121922075))
    (multiple-value-bind (ld lr)
        (truncate a b)
      (multiple-value-bind (gd gr)
          (sb-gmp:mpz-tdiv a b)
        (is (and (= ld gd)
                 (= lr gr))))))
  (let ((a 320613729464106236061704728914573914390)
        (b -285049280629101090500613812618405407883))
    (multiple-value-bind (ld lr)
        (truncate a b)
      (multiple-value-bind (gd gr)
          (sb-gmp:mpz-tdiv a b)
        (is (and (= ld gd)
                 (= lr gr)))))))

(test mpz-nextprime "Test the mpz-nextprime/mpz-probably-prime-p function"
  (sb-gmp:rand-seed *state* 6234)
  (let ((limbs (1+ (random #x2F))))
    (for-all ((a (gen-mpz :limbs limbs)))
      (let ((p (sb-gmp:mpz-nextprime a)))
        (is (>= p a))
        (is (> (sb-gmp:mpz-probably-prime-p p) 0))))))

(test mpq-add "Test the mpq-add function"
  (sb-gmp:rand-seed *state* 1235)
  (dotimes (i 5)
    (let ((limbs (1+ (random #x3FF))))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (an (gen-mpz :limbs limbs))
                (ad (gen-mpz :limbs limbs))
                (bn (gen-mpz :limbs limbs))
                (bd (gen-mpz :limbs limbs)))
        (let ((tan (if (zerop neg-a) an (- an)))
              (tbn (if (zerop neg-b) bn (- bn))))
          (is (= (+ (/ tan ad) (/ tbn bd))
                 (sb-gmp:mpq-add (/ tan ad) (/ tbn bd)))))))))

(test mpq-sub "Test the mpq-sub function"
  (sb-gmp:rand-seed *state* 1235)
  (dotimes (i 5)
    (let ((limbs (1+ (random #x1FF))))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (an (gen-mpz :limbs limbs))
                (ad (gen-mpz :limbs limbs))
                (bn (gen-mpz :limbs limbs))
                (bd (gen-mpz :limbs limbs)))
        (let ((tan (if (zerop neg-a) an (- an)))
              (tbn (if (zerop neg-b) bn (- bn))))
          (is (= (- (/ tan ad) (/ tbn bd))
                 (sb-gmp:mpq-sub (/ tan ad) (/ tbn bd)))))))))

(test mpq-mul "Test the mpq-mul function"
  (sb-gmp:rand-seed *state* 6235)
  (dotimes (i 5)
    (let ((limbs (1+ (random #x5FF))))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (an (gen-mpz :limbs limbs))
                (ad (gen-mpz :limbs limbs))
                (bn (gen-mpz :limbs limbs))
                (bd (gen-mpz :limbs limbs)))
        (let ((tan (if (zerop neg-a) an (- an)))
              (tbn (if (zerop neg-b) bn (- bn))))
          (is (= (* (/ tan ad) (/ tbn bd))
                 (sb-gmp:mpq-mul (/ tan ad) (/ tbn bd)))))))))

(test mpq-div "Test the mpq-div function"
  (sb-gmp:rand-seed *state* 7235)
  (dotimes (i 5)
    (let ((limbs (1+ (random #x3FF))))
      (for-all ((neg-a (gen-integer :min 0 :max 1))
                (neg-b (gen-integer :min 0 :max 1))
                (an (gen-mpz :limbs limbs))
                (ad (gen-mpz :limbs limbs))
                (bn (gen-mpz :limbs limbs))
                (bd (gen-mpz :limbs limbs)))
        (let ((tan (if (zerop neg-a) an (- an)))
              (tbn (if (zerop neg-b) bn (- bn))))
          (is (= (/ (/ tan ad) (/ tbn bd))
                 (sb-gmp:mpq-div (/ tan ad) (/ tbn bd)))))))))
